### ISSUE TITLE
Linux: meson.build:367:22: ERROR: C++ shared or static library 'soci_sqlite3' not found

### ISSUE THREAD

**Issue by csharpee** [brakmic/HDA_with_Cpp#3]
I am building this HDA and have had some trouble when building it on Linux x64. 

I am totally new to the whole C++ build process and fiddled with C++ about 10+ years ago. 

I installed all the packages and updated the triplet + the vcpkg home.

I run the following command: `./buildall.sh` on Linux.

```
Compiler stderr:

Library drogon found: YES
Library trantor found: YES
Library jsoncpp found: YES
Library ssl found: YES
Library crypto found: YES
Library brotlicommon-static found: YES
Library brotlienc-static found: YES
Library brotlidec-static found: YES
Library cares found: YES
Library z found: YES
Library fmt found: YES
Library sqlite3 found: YES
Library soci_core found: YES

meson.build:367:22: ERROR: C++ shared or static library 'soci_sqlite3' not found
```
ln 367 of meson.build
```
libsoci_sqlite3 = cpp.find_library(
    soci_sqlite3_name,
    dirs: [vcpkg_root / 'packages/soci_' + triplet + '/lib'],
)
```

The packages in that directory are: 

![image](https://github.com/brakmic/HDA_with_Cpp/assets/18726788/cd2d54d5-b27c-422c-af7a-9e9bfa4bcc07)

Solution: :heavy_check_mark: 
I had to rebuild the vcpkg for some odd reason and that solved the problem, but now I am having a *Criterion* library not found. 

`vcpkg install soci[sqlite3] --recurse` rebuilt everything and fixed the issue.

**Comment by csharpee** [comment]
The criterion error:
```
meson.build:390:19: ERROR: C++ shared or static library 'criterion' not found
```

ln 390 of meson.build
```
# Criterion test library

libcriterion_name = 'criterion'
libcriterion = cpp.find_library(
    libcriterion_name,
    dirs: [criterion_libs],
)
```

**Comment by csharpee** [comment]
The ninja build error: 

```
[14/14] Linking target demo_web_server
...
c.o): in function `drogon::utils::getUuid[abi:cxx11]()':
Utilities.cc:(.text+0x905): undefined reference to `uuid_generate'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by csharpee** [comment]
The PR has been created @brakmic https://github.com/brakmic/HDA_with_Cpp/pull/5

**Comment by brakmic** [comment]
Many thanks for your patches! I merged them.
