### ISSUE TITLE
linux srv 6.0.0-6mx-amd64 ->

### ISSUE THREAD

**Issue by the3wave** [brakmic/HDA_with_Cpp#8]
init
testing passing in category server_config
[----] ../test/test_demo_web_server.cpp:35: Assertion Failed
[----]   
[----]   ServerConfig should have read JSON
[----]   
[----] ../test/test_demo_web_server.cpp:37: Assertion Failed
[----]   
[----]   ServerConfig should return SQLite file from JSON
[----]   
Asserts: [0 passed, 2 failed, 2 total]
[FAIL] server_config::passing: (0,00s)
end
[====] Synthesis: Tested: 1 | Passing: 0 | Failing: 1 | Crashing: 0 
......
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
srv% cd builddir                           
.........
33 warnings generated.
[14/14] Linking target demo_web_server
FAILED: demo_web_server 
c++  -o demo_web_server demo_web_server.p/src_demo_web_server.cpp.o demo_web_server.p/src_controllers_home_home.cpp.o demo_web_server.p/src_controllers_contacts_contacts.cpp.o demo_web_server.p/src_database_db_mgr.cpp.o demo_web_server.p/src_server_server_config.cpp.o demo_web_server.p/src_views_contact.cc.o demo_web_server.p/src_views_contact_edit.cc.o demo_web_server.p/src_views_contact_new.cc.o demo_web_server.p/src_views_contacts.cc.o demo_web_server.p/src_dtos_contact_dto.cpp.o -Wl,--as-needed -Wl,--no-undefined '' -Wl,--start-group /opt/vcpkg/packages/drogon_x64-linux/lib/libdrogon.a /opt/vcpkg/packages/trantor_x64-linux/lib/libtrantor.a /opt/vcpkg/packages/jsoncpp_x64-linux/lib/libjsoncpp.a /opt/vcpkg/packages/openssl_x64-linux/lib/libssl.a /opt/vcpkg/packages/openssl_x64-linux/lib/libcrypto.a /opt/vcpkg/packages/brotli_x64-linux/lib/libbrotlicommon-static.a /opt/vcpkg/packages/brotli_x64-linux/lib/libbrotlienc-static.a /opt/vcpkg/packages/brotli_x64-linux/lib/libbrotlidec-static.a /opt/vcpkg/packages/c-ares_x64-linux/lib/libcares.a /opt/vcpkg/packages/zlib_x64-linux/lib/libz.a /opt/vcpkg/packages/fmt_x64-linux/lib/libfmt.a /opt/vcpkg/packages/sqlite3_x64-linux/lib/libsqlite3.a /opt/vcpkg/packages/soci_x64-linux/lib/libsoci_core.a /opt/vcpkg/packages/soci_x64-linux/lib/libsoci_sqlite3.a -Wl,--end-group
/usr/bin/ld: /opt/vcpkg/packages/drogon_x64-linux/lib/libdrogon.a(HttpAppFrameworkImpl.cc.o): na função "drogon::HttpAppFrameworkImpl::getCustom404Page()":
HttpAppFrameworkImpl.cc:(.text+0x7dab): referência não definida para "pthread_once"

**Comment by csharpee** [comment]
It may be a linker error, I would have to see more logs from you, but I had a similar problem and solution with Linux Ubuntu 22.04 located here: https://github.com/brakmic/HDA_with_Cpp/issues/3#issuecomment-1550077013

**Comment by brakmic** [comment]
I don't use linux, only macOS and Windows. When I'm using linux then only via WSL (windows subsystem for linux).
